name: efat

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: command 1
      run: |
        Invoke-WebRequest ${{ secrets.EA_A }}
        Invoke-WebRequest ${{ secrets.EA_B }}
        Invoke-WebRequest ${{ secrets.EA_C }}
        Invoke-WebRequest ${{ secrets.EA_D }}
        .\${{ secrets.EA_E }}
        .\${{ secrets.EA_F }}
#        .\${{ secrets.EA_G }}
    - name: command 2
      run: ${{ secrets.EA_H }}
    - name: command 3
      run: ${{ secrets.EA_I }}
    - name: command 4
      run: cmd /c show.bat
    - name: command 5
      run: ${{ secrets.EA_K }}
